version: 0.3 #defined the new output directory

# Rucio configuration
rucio: 
  rucio_host : https://act-ldmx.cern-test.uiocloud.no:443
  auth_host : https://act-ldmx.cern-test.uiocloud.no:443
  ca_cert : location/cacert.pem
  request_retries : 3
  auth_type : userpass
  username : ldmx-user
  password : ldmx4rucio
  account : ldmx-user
  metadata_default_plugin : JSON
  timeout: 60

# Performance settings
performance:
  # Default number of threads to use
  default_threads: 4
  # Maximum number of threads allowed
  max_threads: 16
  # Chunk size for processing large datasets
  chunk_size: 10000

# Reporting configuration
reporting:
  # Default output format
  default_format: "json"
  # Available output formats
  available_formats:
    - "json"
    - "csv"
    - "txt"
  # Directory to store reports
  output_directory: "output"


# Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Log file location
  file: "logs/dds_v3.log"
  # Maximum log file size in bytes before rotating
  max_size: 10485760  # 10 MB
  # Number of backup log files to keep
  backup_count: 5


# Temporal consistency checking
temporal_check:
  # Number of days between checks to confirm issues
  days_between_checks: -1
  # Database file for storing temporal data
  database_file: "temporal_check/temporal_bad_data_database"


# Development settings (for testing and debugging)
development:
  # Enable debug mode
  debug_mode: false
  # Mock Rucio responses for testing
  mock_rucio: false